### ISSUE TITLE
Add environment variable for topic auto-creation [Feature Request]

### ISSUE THREAD

**Issue by sathiz1993** [bitnami/bitnami-docker-kafka#11] opened 2018-05-05 08:33 UTC
Add environment variable for enabling the topic auto-creation

**Comment by andresbono** [comment] 2018-05-07 11:15
Hi @sathiz1993, could you give us more details about the feature you want to be included in this container? e.g:

- What is the configuration parameters that need to be modified in Kafka?
- What is the expected behavior once implemented?

Thanks!
-Andrés B.

**Comment by sathiz1993** [comment] 2018-05-07 13:34
Hello @andresbono,
You need to add the property `auto.create.topics.enable=true` in server.properties file and make it configurable via env. 
Auto topic creation will be useful for dev environments. 


For production environments provide something like array of topics to be created via env.
                         `KAFKA_TOPICS: "Topic1:1:3,Topic2:1:1"`
These topics should be created after kafka start with following configuration
Topic 1 will have 1 partition and 3 replicas
Topic 2 will have 1 partition, 1 replica

Thanks in Advance

**Comment by andresbono** [comment] 2018-05-08 08:42
@sathiz1993, thanks for providing more information about the feature request! We will evaluate it and we will see if it makes sense to have it included in our container.

In the meantime, we will keep this issue opened.

Thanks again for the valuable feedback!
-Andrés B.

**Comment by jgracin** [comment] 2019-07-23 14:17
Hi! Is there any chance you make this option overridable via KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE?  Automatic creation of topics is a nuisance in production (and similar) enviroments.  Thanks!

**Comment by andresbono** [comment] 2019-07-25 09:37
Thanks for the tip, @jgracin. We will try to prioritize this feature request and we will keep in mind your suggestion.

**Comment by marcosbc** [comment] 2019-09-17 13:54
Hi @jgracin, I was just checking this and I understand the container already supports this environment variable.

For instance, if you run the container in the following way:

```
docker run -ti -e "KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false" -e ALLOW_PLAINTEXT_LISTENER=true bitnami/kafka
```

Then the property will be added to `server.properties`:
```
auto.create.topics.enable=false
```

Which should be valid according to the [Kafka documentation](https://kafka.apache.org/documentation/).

**Comment by jgracin** [comment] 2019-09-18 07:31
@marcosbc Hi Marcos!  I think this feature was added in 2.3.0 and it is not supported in 2.2.0 Kafka images. I guess I'll just upgrade.  Thanks!

**Comment by marcosbc** [comment] 2019-09-18 09:37
Hi @jgracin, actually it was added to `2.2.0-debian-9-r40` (and a related fix was included in `2.2.1-debian-9-r16`).

Since it seems this issue is solved, I'll proceed to close this ticket.

**Closed** 2019-09-18 09:37 UTC
Labels: on-hold

**Comment by Mauraza** [comment] 2020-02-13 15:53
Hi @sathiz1993 and @jgracin, in the new version (`2.4.0-debian-10-r17`), you can use the `auto.create.topics.enable` property by setting the `KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE`. It is a boolean so  `true` or `false` are the valid values, the default is `true`.
For example:
```bash
docker run --name kafka  -e KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true bitnami/kafka:latest
```
In this case, the property will be added to the file `server.properties`:
```properties
auto.create.topics.enable=true
port=9092
```
Is it valid for you?

**Comment by jgracin** [comment] 2020-02-15 20:26
Hi @Mauraza, that's perfect, thanks!
