### ISSUE TITLE
Kafka SSL Not Working

### ISSUE THREAD

**Issue by yangzaizi** [bitnami/bitnami-docker-kafka#146] opened 2021-02-22 10:36 UTC
Here is my docker-compose file

[docker-compose.txt](https://github.com/bitnami/bitnami-docker-kafka/files/6021273/docker-compose.txt)

Essentially followed instruction on https://github.com/bitnami/bitnami-docker-kafka to set up ssl.

I used the script mentioned to generate the jks files. I also tried to give my kafka container a hostname: kafka.com.

But when I docker exec into my container and try to run the producer or consumer shell scripts, I get ssl handshake exception.

Also I created a bridge network so that my containers can be reached by other containers on the same network.

Also gave each container a container name.

Any help appreciated. 

Not really sure in my setup, what exactly should I put for the fqdn when running that certificate generating script.

I am running this in my ubuntu machine.

**Comment by migruiz4** [comment] 2021-02-23 12:50
Hi @yangzaizi,

I found an issue when using SASL_SSL and running the consumer script, it won't work with the following error:
```

I have no name!@kafka:/$ kafka-console-producer.sh --bootstrap-server kafka.com:9092 --topic test --producer.config /opt/bitnami/kafka/config/producer.properties
>[2021-02-23 12:33:28,783] WARN [Producer clientId=console-producer] Bootstrap broker kafka.com:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2021-02-23 12:33:29,001] WARN [Producer clientId=console-producer] Bootstrap broker kafka.com:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2021-02-23 12:33:29,161] WARN [Producer clientId=console-producer] Bootstrap broker kafka.com:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2021-02-23 12:33:29,320] WARN [Producer clientId=console-producer] Bootstrap broker kafka.com:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2021-02-23 12:33:29,480] WARN [Producer clientId=console-producer] Bootstrap broker kafka.com:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```

The issue can be fixed by adding the properties `security.protocol` and `sasl.mechanism` to the consumer and producer.
To fix this issue, could you please try with the following?

```bash
#Copy the producer file
cp /opt/bitnami/kafka/config/producer.properties  /opt/bitnami/kafka/config/producer_sasl.properties
#Add the SASL properties
echo "sasl.mechanism=PLAIN
security.protocol=SASL_SSL" >> /opt/bitnami/kafka/config/producer_sasl.properties

#Run the producer script
export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf"
kafka-console-producer.sh --bootstrap-server kafka.com:9092 --topic test --producer.config /opt/bitnami/kafka/config/producer_sasl.properties
```

For the consumer script, apply the same fix but replacing `producer` with `consumer`
```bash
#Copy the consumer file
cp /opt/bitnami/kafka/config/consumer.properties /opt/bitnami/kafka/config/consumer_sasl.properties
#Add the SASL properties
echo "sasl.mechanism=PLAIN
security.protocol=SASL_SSL" >> /opt/bitnami/kafka/config/consumer_sasl.properties

#Run the producer script
export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf"
kafka-console-consumer.sh --bootstrap-server kafka.com:9092 --topic test --from-beginning --consumer.config /opt/bitnami/kafka/config/consumer_sasl.properties
```

Please let me know if it worked.

**Comment by yangzaizi** [comment] 2021-02-25 00:41
Thanks for your help. I manage to figure things out. Yeah that thing worked.

**Comment by migruiz4** [comment] 2021-02-25 07:19
Great! I'm happy the issue is now resolved.

In that case, I'm going to proceed to close this issue.

**Closed by migruiz4** 2021-02-25 07:19 UTC
