### ISSUE TITLE
Cannot produce message to Kafka container from Windows host

### ISSUE THREAD

**Issue by charithf** [bitnami/bitnami-docker-kafka#21] opened 2018-08-20 11:58 UTC
Hi,

I'm logging this issue just to get some support. I'm not sure whether this is a configuration issue.

- I am using https://github.com/bitnami/bitnami-docker-kafka
- I have created a simple zookeeper/kafka instance via docker-compose

```
services:
zookeeper:
image: 'bitnami/zookeeper:latest'
ports:
- '2181:2181'
volumes:
- 'C:/RandD/KafkaRun/bitnami2/zookeeper_data:/bitnami'
environment:
- ALLOW_ANONYMOUS_LOGIN=yes
kafka:
image: 'bitnami/kafka:latest'
ports:
- '9092:9092'
volumes:
- 'C:/RandD/KafkaRun/bitnami2/kafka_data:/bitnami'
environment:
- KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
- KAFKA_BROKER_ID=1
- KAFKA_LOG_RETENTION_HOURS=1
- ALLOW_PLAINTEXT_LISTENER=yes
```

From the host when i check the available topics list it works and shows me the list

I tried running the following command from windows host to produce 
%KAFKA_HOME%\bin\windows\kafka-console-producer.bat --broker-list localhost:9092 --topic audit21
I get the following error:
[2018-08-20 10:50:06,391] ERROR Error when sending message to topic audit21 with key: null, value: 19 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 2 record(s) for audit21-0: 2305 ms has passed since batch creation plus linger time

I'm not sure what i am doing wrong here as i have exposed/mapped the ports in the compose file

**Comment by codejnki** [comment] 2018-08-20 13:49
This is probably not an ideal solution, but I was able to work around this.  I feel like the hosts file modification is a hack so if there is a better way to do this I'd like to know.

In my docker-compose.yml file I set up the following

```
  kafka:
    hostname: 'kafka'
    image: 'bitnami/kafka:2.0.0'
    ports:
      - '9092:9092'
    environment: 
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
```

In my hosts file I added an entry

```
127.0.0.1 kafka
```

Now local host applications and other containers in the same container network are able to connect to the kafka instance.

**Comment by charithf** [comment] 2018-08-20 15:57
This solution is working. I'm wondering why. Usually in my other R&D tasks, I have managed to just expose the port and map to localhost and it works without a problem without changing the host file.

**Comment by codejnki** [comment] 2018-08-20 16:33
I think it has to do with the way kafka specifically works and how kafka clients learn about the brokers.

When a kafka client connects you give it the --bootstrap.server option, then kafka tells the client about the names of the other machines.  Kafka by default gives out the host name.  If that hostname isn't resolvable outside the docker network, then bad times ensue.

**Comment by marcosbc** [comment] 2018-08-21 10:44
Hi all, I'm glad you were able to resolve the issues! Kafka effectively needs its hostname to be resolvable inside the network.

In our README, we also recommend users to run the Docker image as client. This way you don't need to worry about downloading it locally and configuring it, and it is also directly inside your network.
Read more about it [here](https://github.com/bitnami/bitnami-docker-kafka/#step-3-launch-your-kafka-client-instance).

**Comment by cricket007** [comment] 2018-11-01 00:36
Editing the hosts file is definitely a hack. You're supposed to expose two ports. One for internal Docker traffic, and another for external clients.

https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by marcosbc** [comment] 2018-11-01 12:49
@cricket007 I remember it had something to do with how Kafka initializes, as it would use "kafka" as hostname but I did not inspect further. It could be possible the issue is with KAFKA_LISTENERS and KAFKA_ADVERTISED_LISTENERS not being set properly.

**Comment by cricket007** [comment] 2018-11-01 23:05
Tested on Mac with these settings

  ```yaml
ports:
 - 9092
 - 29092
environment:
 ...
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
  KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
```

Producer, outside of container

```bash
$ kafka-console-producer --broker-list localhost:29092 --topic test
>hello world
[2018-11-01 17:45:16,135] WARN Error while fetching metadata with correlation id 1 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2018-11-01 17:45:16,247] WARN Error while fetching metadata with correlation id 3 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
>sample
>text
>interesting
```

And consumer outside of container

```bash
$ kafka-console-consumer --bootstrap-server localhost:29092 --topic test --from-beginning
hello world
sample
text
interesting
^CProcessed a total of 4 messages
```

**Comment by marcosbc** [comment] 2018-11-05 12:29
Thank you @cricket007! PLAINTEXT_HOST seems to do the trick. We'll look into documenting this in the README.

**Comment by shani530** [comment] 2020-04-20 06:03
I am facing the same issue . Not able to send messages from Java client from my localhost.
 version: '3'

 services:

  zookeeper:
    image: "wurstmeister/zookeeper"
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    hostname: 'kafka'
    image: "wurstmeister/kafka:latest"
    container_name: kafka
    depends_on:
     - zookeeper
    ports:
     - "9093:9093"
     - "9092:9092"
     
    #hostname: kafka
    volumes:
      - ./ssl/server.keystore.jks:/ssl/server.keystore.jks
      - ./ssl/server.truststore.jks:/ssl/server.truststore.jks
    environment:
        
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_LISTENERS: 'SSL://:9093,PLAINTEXT://:9092,PLAINTEXT_HOST://:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL:SSL'
      KAFKA_ADVERTISED_LISTENERS: 'SSL://:9093,PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'SSL'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "order-topic:3:1,orderStatus-topic:3:1"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_SSL_KEYSTORE_LOCATION: '/ssl/server.keystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: 'test1234'
      KAFKA_SSL_KEY_PASSWORD: 'test1234'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/ssl/server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 'test1234'

**Comment by cricket007** [comment] 2020-04-20 06:58
@shani530 If you would like to post an issue here, please use the Docker image listed in the README.

**Comment by cricket007** [comment] 2020-04-20 06:59
Your issue exists here. 

```
ports:
- "9093:9093"
- "9092:9092"
```

**Comment by shani530** [comment] 2020-04-20 08:33
Not able to post messages from windows machine .  
I am trying hitting without ssl .
command :kafka-console-producer.bat --broker-list localhost:29092 --topic order-topic

 Getting error :  E:\Kafka Learning Udemy\OrderManagementAndFulfilmentApp\scripts>kafka-console-producer.bat --broker-list localhost:29092 --topic order-topic 
>[2020-04-20 13:57:25,575] WARN [Producer clientId=console-producer] Connection to node -1 (localhost/127.0.0.1:29092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2020-04-20 13:57:26,628] WARN [Producer clientId=console-producer] Connection to node -1 (localhost/127.0.0.1:29092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

Updated docker compose file-->
version: '3'

 services:

  zookeeper:
    image: "wurstmeister/zookeeper"
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    hostname: 'kafka'
    image: "wurstmeister/kafka:latest"
    container_name: kafka
    depends_on:
     - zookeeper
    ports:
     - "9093:9093"
     - "9092:9092"
     - "29092:29092"
     
    #hostname: kafka
    volumes:
      - ./ssl/server.keystore.jks:/ssl/server.keystore.jks
      - ./ssl/server.truststore.jks:/ssl/server.truststore.jks
    environment:
        
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_LISTENERS: 'SSL://:9093,PLAINTEXT://:9092,PLAINTEXT_HOST://:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL:SSL'
      KAFKA_ADVERTISED_LISTENERS: 'SSL://:9093,PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'SSL'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "order-topic:3:1,orderStatus-topic:3:1"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_SSL_KEYSTORE_LOCATION: '/ssl/server.keystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: 'test1234'
      KAFKA_SSL_KEY_PASSWORD: 'test1234'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/ssl/server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 'test1234'

**Comment by shani530** [comment] 2020-04-20 12:42
Issue is resolved by making change here :
KAFKA_ADVERTISED_LISTENERS: 'SSL://:9093,PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.99.100:29092'.

Need to change localhost to 192.168.99.100(IP address)

**Comment by marcosbc** [comment] 2020-04-20 16:45
Great to hear @shani530! In the case of docker-compose environments that needs to be set to the proper value, unless you enable a DNS for that. In Helm charts it is [different](https://github.com/bitnami/charts/tree/master/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster) though.

Since this issue seems to be resolved, I'm proceeding to close it.

**Closed** 2020-04-20 16:48 UTC
Labels: on-hold
