### ISSUE TITLE
Provide Kafka 3.x container without Zookeeper

### ISSUE THREAD

**Issue by matthewadams** [bitnami/bitnami-docker-kafka#223] opened 2022-02-02 15:27 UTC
**Description**

The current containers at https://github.com/bitnami/bitnami-docker-kafka have `docker-compose.yml` files that include Zookeeper, which is no longer required as of Kafka 2.8.0.

**Steps to reproduce the issue:**

1. Run `docker-compose.yaml` as provided by `curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-kafka/master/3/debian-10/docker-compose.yml`

**Describe the results you received:**

Observe that there is a zookeeper _and_ a Kafka container running.

**Describe the results you expected:**

No Zookeeper container running, only Kafka configured to use KRaft.

**Comment by juan131** [comment] 2022-02-03 07:00
Duplicate of https://github.com/bitnami/bitnami-docker-kafka/issues/159

**Closed by juan131** 2022-02-03 07:00 UTC

**Comment by matthewadams** [comment] 2022-02-03 15:58
Oops soory for the dup
